### ISSUE TITLE
v4 alpha3 Bootstrap generates error "Cannot find module 'Bootstrap'"

### ISSUE THREAD

**Issue by csprocket777** [bennycwong/ember-bootstrap-4#8] opened 2016-07-28 19:24 UTC
It looks like alpha3 of bootstrap in NPM comes precompiled and doesn't work the way alpha 2 did. There is no 'Bootstrap' exported module. (?)

**Comment by ignotus0001** [comment] 2016-08-01 04:07
Yeah a new install just got me with this as well.

**Comment by erichaus** [comment] 2016-08-01 06:09
crap im getting this too... anyone have a suggestion?

**Comment by csprocket777** [comment] 2016-08-01 14:05
I'm hoping the package authors pick this up. I'm not seeing an alpha3 repo that structures the files the same was as alpha2 did. It would require changing how the add-on includes bootstrap and I'm not comfortable doing that.

**Comment by erichaus** [comment] 2016-08-01 14:55
ok any eta or short-term solution? should I include bootstrap a different way? this is now blocking my client app!

**Comment by csprocket777** [comment] 2016-08-01 16:07
Are you needing alpha3? If not, change your package.json to read the alpha2 version like this:

```
"bootstrap": "4.0.0-alpha.2",
```

and you should be fine.

**Comment by bennycwong** [comment] 2016-08-01 17:01
Hey guys, I'd take a look a kaermorchen's ember bootstrap 4 instead of this one. I'm built this add-on for a toy app I was building and haven't touched it since. Kaermorchen's looks more up to date. Hopefully that'll solve your problems!

https://github.com/kaermorchen/ember-cli-bootstrap-4

**Comment by rudymacias** [comment] 2016-08-12 20:19
Found the quick/patch fix. Change the main path within this file "node_modules/bootstrap/package.json" from

`"main": "./dist/js/npm"`

to

`"main": "dist/js/bootstrap"`

The issue is due to Bootstrap v4.0.0-alpha.3 was committed with this issue. Not an issue from this Ember addon.

**Comment by erichaus** [comment] 2016-08-12 21:15
@rudymacias submit pr?

**Comment by bennycwong** [comment] 2016-08-12 23:04
I pinned the alpha 2 version of bootstrap to the latest release of ember-bootstrap-4 (0.1.1). I think this should fix the issue.

@rudymacias @csprocket777 @ignotus0001 @erichonkanen

**Comment by ve3** [comment] 2016-09-08 07:41
My package.json dependency is just like this. `"ember-bootstrap-4": "0.1.1",`
There is no `"bootstrap": "4.0.0-alpha.2",`

How to change to v4 alpha3?

**Comment by juliankmazo** [comment] 2016-09-09 21:28
@bennycwong  With alpha 4 the issue is solved, so you can unpin the alpha 2 version. Everything works just fine with the alpha 4 version.

**Comment by bennycwong** [comment] 2016-09-10 01:24
@juliankmazo This has been updated. Please give it a try.

**Closed as completed** 2016-09-10 04:35 UTC
